version: "3.8"

services:
  dcs-postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
     - dcs-postgres
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    environment:
      ENV: localhost 

volumes:
  data:
    driver: local
